[font.normal]
family = "FiraCode Nerd Font"

[font]
size = 16

[window]
decorations = "none"

[window.padding]
x = 10
y = 10

[env]
TERM = "xterm-256color"

[shell]
program = "/bin/zsh"
args = ["-l", "-c", "tmux attach || tmux"]
